// <auto-generated />
// ReSharper disable All
using System;
using Android.App;
using Android.Support.V7.Widget;
using Android.Views;
using Android.Widget;

namespace VacationsTracker.Android.Views
{
    public partial class LoginActivityViewHolder
    {
         private readonly Activity activity;

         private TextView _InvalidCredentialsText;
         private EditText _LoginEntry;
         private EditText _PasswordEntry;
         private Button _LoginButton;

        public LoginActivityViewHolder( Activity activity)
        {
            if (activity == null) throw new ArgumentNullException(nameof(activity));

            this.activity = activity;
        }

        
        public TextView InvalidCredentialsText =>
            _InvalidCredentialsText ?? (_InvalidCredentialsText = activity.FindViewById<TextView>(Resource.Id.InvalidCredentialsText));

        
        public EditText LoginEntry =>
            _LoginEntry ?? (_LoginEntry = activity.FindViewById<EditText>(Resource.Id.LoginEntry));

        
        public EditText PasswordEntry =>
            _PasswordEntry ?? (_PasswordEntry = activity.FindViewById<EditText>(Resource.Id.PasswordEntry));

        
        public Button LoginButton =>
            _LoginButton ?? (_LoginButton = activity.FindViewById<Button>(Resource.Id.LoginButton));
    }
}
// ReSharper restore All
